parameters:
    it_blaster_seo.admin.seo_param.class:  ItBlaster\SeoBundle\Admin\SeoParamAdmin
    it_blaster_seo.admin.seo_file.class: ItBlaster\SeoBundle\Admin\SeoFileAdmin
    it_blaster_seo.admin.seo_counter.class: ItBlaster\SeoBundle\Admin\SeoCounterAdmin

services:
    it_blaster_seo.admin.seo_param:
        class: %it_blaster_seo.admin.seo_param.class%
        tags:
            - { name: sonata.admin, manager_type: propel, group: SEO, label: seo_param_label }
        arguments: [~, ItBlaster\SeoBundle\Model\SeoParam, ~]

    it_blaster_seo.admin.seo_file:
        class: %it_blaster_seo.admin.seo_file.class%
        arguments: [~, ItBlaster\SeoBundle\Model\SeoFile, ItBlasterSeoBundle:SeoFileAdmin]
        tags:
            - {name: sonata.admin, manager_type: propel, group: SEO, label: seo_files_label}

    it_blaster_seo.admin.seo_counter:
        class: %it_blaster_seo.admin.seo_counter.class%
        arguments: [~, ItBlaster\SeoBundle\Model\SeoCounter, ~]
        tags:
            - { name: sonata.admin, manager_type: propel, group: SEO, label: seo_counters_label }
